"""Intent taxonomy package."""
from intent.taxonomy import INTENTS, INTENT_NAMES, INTENT_DESCRIPTIONS, ESCALATION_DEFAULTS, ESCALATION_NOTES

__all__ = ["INTENTS", "INTENT_NAMES", "INTENT_DESCRIPTIONS", "ESCALATION_DEFAULTS", "ESCALATION_NOTES"]
